CLASS zcx_unknown_entity DEFINITION
  PUBLIC
  INHERITING FROM cx_sadl_exit
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcx_unknown_entity IMPLEMENTATION.
ENDCLASS.
