 CLASS ztcl_c_purchasedocumentlrp  DEFINITION
 PUBLIC
 FINAL
 CREATE PUBLIC
 FOR TESTING.

   PUBLIC SECTION.
   PROTECTED SECTION.
   PRIVATE SECTION.
 ENDCLASS.

 CLASS ztcl_c_purchasedocumentlrp  IMPLEMENTATION.
 ENDCLASS.
