 CLASS ztcl_i_purchdocoverallprice  DEFINITION
 PUBLIC
 FINAL
 CREATE PUBLIC
 FOR TESTING.

   PUBLIC SECTION.
   PROTECTED SECTION.
   PRIVATE SECTION.
 ENDCLASS.

 CLASS ztcl_i_purchdocoverallprice  IMPLEMENTATION.
 ENDCLASS.
